
services:
  react-electoral-map:
    container_name: react-electoral-map
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${REACT_ELECTORAL_MAP_PORT}:80"
    restart: unless-stopped
