
services:
  electoral-map:
    container_name: electoral-map
    environment:
      ENV: ${ENV}
    image: incerto13/react-electoral-map:${ENV}-latest
    restart: unless-stopped
    build: .
    ports:
      - 8012:80
