# only run from context of parent incerto-k8 directory when orchestrating all portfolio apps in local dev

services:
  electoral-map:
    container_name: electoral-map
    restart: unless-stopped
    build: 
      context: react-electoral-map/
      dockerfile: Dockerfile
    ports:
      - 8012:80
