
services:
  react-electoral-map:
    container_name: react-electoral-map
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: ${ENV}
    image: incerto13/react-electoral-map:${ENV}-latest
    restart: unless-stopped
    ports:
      - 8012:80
